### ISSUE TITLE
Hiding format symbols

### ISSUE THREAD

**Issue by alyrik** [s-yadav/react-number-format#108]
**Format**: `"## ###-##-##"`.

**Result**: Non-numeric symbols (`-`) are shown as a user starts typing ([demo](https://codepen.io/alyrik/pen/OxKYvr))

**Expected result (which is actual for v2)**: Non-numeric symbols (`-`) are shown one by one when a user types a numeric symbol after a non-numeric one ([demo](https://codepen.io/alyrik/pen/KXOLgL))

**Comment by s-yadav** [comment]
This is intentional. This was added to fix formatting issues when there is number is on the format, take example of phone numbers, +1 (###) ### ## . In this, we have to keep the format as it is which will look like +1 (   )        so that we can distinguish between user input and format. 
You can give mask character so it doesn't look odd. Having mask _ it will look , +1 (___) ____ __

**Comment by guitexa** [comment]
> 
> 
> **Format**: `"## ###-##-##"`.
> 
> **Result**: Non-numeric symbols (`-`) are shown as a user starts typing ([demo](https://codepen.io/alyrik/pen/OxKYvr))
> 
> **Expected result (which is actual for v2)**: Non-numeric symbols (`-`) are shown one by one when a user types a numeric symbol after a non-numeric one ([demo](https://codepen.io/alyrik/pen/KXOLgL))

Hey @alyrik how did you do this [demo](https://codepen.io/alyrik/pen/KXOLgL) without symbols?

I really need to create an input field with format but without show symbols, if someone can help I appreciate.

![format number(2)](https://user-images.githubusercontent.com/34251231/93036941-92745680-f617-11ea-92bd-695bf7b311d6.gif)
