### ISSUE TITLE
Setting onValueChange caused React issue

### ISSUE THREAD

**Issue by businessnumbertwo** [s-yadav/react-number-format#118]
Hello,

When I try an use the onValueChange prop, e.g. :

```
  <NumberFormat value={this.state.profit} prefix="$" onValueChange={(values) => {
    const {formattedValue, value} = values;
    // formattedValue = $222,3
    //value ie, 2223
    this.setState({profit: value})
  }}/>
```

React reports the following in the console:

`proxyConsole.js:56 Warning: Unknown event handler property `onValueChange`. It will be ignored.
`

Kind regards, Phil

**Comment by s-yadav** [comment]
Are you using v3 or v2 ? This prop is added on v3. and it shouldn't give that warning in v3.

**Comment by mdAlvarenga** [comment]
Hello, I have a question about using in the `onChange` and `onValueChange`, since I am needing the `id` of the `event.target` and the value **without format**. And from what I was reading about `onValueChange`, I can not get the target id. I hope you understand my question because I do not write English very well and i use google translate :)  Thanks and regards

**Comment by s-yadav** [comment]
You can pass both onChange and onValueChange together. However, if you just need an id of the target to uniquely identify it, you can do something like

```jsx
<Numberformat value={this.state.price} id="price" onValueChange={this.handleChange.bind(this, 'price')}/>
```
```js
handleChange(id, values) {
  const {value} = values; // non formatted value.
}
```

**Comment by mdAlvarenga** [comment]
It works! Thanks!

**Comment by businessnumbertwo** [comment]
Ah yes I am using v2. Is v3 available through npm yet?

Many thanks for this super package

Phil
