### ISSUE TITLE
Error while using NumberFormat component

### ISSUE THREAD

**Issue by ThibDacodac** [s-yadav/react-number-format#203]
Hi,

I have a very strange issue. I was using "NumberFormat" component for the past four months without any issue (thanks again for this by the way, it's very useful !)

But, unfortunately, I have a weird issue on a new React project I'm working on :
- In my packages.config I have : "react-number-format": "^3.3.1".
- In my .tsx file, I have :
`import * as NumberFormat from 'react-number-format';`
[...]
`<NumberFormat value={12345} displayType={'text'} thousandSeparator={true} prefix={'$'} />`

But :
- After a "npm install", I got the following error :
**[ts] JSX element type 'NumberFormat' does not have any construct or call signatures.**
(which is weird, because this used to work fine before)

So I changed my import to :
`import { default as NumberFormat } from 'react-number-format';`

And I don't have this error anymore.

But, instead I get this error in the Console when using the component :
**Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `CellElement`.**

FYI, my CellElement is a component :

export class CellElement extends React.Component<any, any> {
  render() {
    [...]
    <NumberFormat value={12345} displayType={'text'} thousandSeparator={true} prefix={'$'} />
  }

I don't understand what's happening. I haven't changed the version I'm using.

Do you know what could cause this issue ?

Many thanks for your help,

Thibaut

**Comment by s-yadav** [comment]
@horacehylee ^

**Comment by horacehylee** [comment]
I will take a look into it.

**Comment by horacehylee** [comment]
@ThibDacodac what is your tsconfig.json?

**Comment by s-yadav** [comment]
I think this is because there was no default export in module, but in ts it was defined as default export. Fixed this now on v3.5.0. 
@horacehylee,  @ThibDacodac . Can you confirm it got fixed.
Also can you check if just `import NumberFormat from 'react-number-format';` works on type script as well ?

**Comment by ThibDacodac** [comment]
Thanks for your reply. I still get the error though with v3.5.0 :

[...]\node_modules\fbjs\lib\invariant.js:42 Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

**Comment by horacehylee** [comment]
@s-yadav I made a sample project with Typescript [link](https://github.com/horacehylee/react-number-format/tree/feature/typescript-testing/example-typescript)
Both `import NumberFormat from 'react-number-format';` and `import {default as NumberFormat } from 'react-number-format';` is working for the latest version.

**Comment by horacehylee** [comment]
@s-yadav After a bit more digging, I found out that for running test cases in test runner (i.e. jest), the module import handling is different than using webpack or other bundlers. 

I would suggest using [babel-plugin-transform-es2015-modules-umd](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-umd/) instead of `babel-plugin-add-module-exports` to export the module, which will export to `umd` style and have same module behaviour across all Javascript environments.

I added a test case in [feature/typescript-example](https://github.com/horacehylee/react-number-format/tree/feature/typescript-testing/example-typescript), which replaces with babel umd plugin. Otherwise, the test case will fail with `React.createElement: type is invalid
-- expected a string (for built-in components) or
a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`, which is the same as @ThibDacodac, while using bundler like `parcel` is working find.

**Comment by horacehylee** [comment]
#180

**Comment by s-yadav** [comment]
We can't use babel-plugin-transform-es2015-modules-umd. That is something which webpack take care. I will check on the branch. I tried this on some random codesandbox for typescript https://codesandbox.io/s/74xr9m9ym1
If I use `import * as NumberFormat from 'react-number-format'` it works. But `import {default as NumberFormat} from 'react-number-format'` throws error. May be we can look the difference on your configuration and the code sandbox one.

**Comment by jakub-astrahit** [comment]
I have the same problem as the original poster @ThibDacodac . My nodeJS version is v6.12.3.
From package.json:
    "react-number-format": "^3.5.0",

@s-yadav 
> import * as NumberFormat from "react-number-format"

This does NOT work using the nodeJS v6.12.3. It gives me the following error:

`TS2604: JSX element type 'NumberFormat' does not have any construct or call signatures.
webpack: Failed to compile.`

@horacehylee Your imports also fail using nodeJS v6.12.3.

Also note that on my project I cannot upgrade to a newer version of nodeJS due to security/policy that I have no control over.

Using this import:

`import NumberFormat from "react-number-format"`

does NOT work either. It compiles OK, but fails in the browser - it gives me these errors:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by s-yadav** [comment]
@horacehylee, @ThibDacodac, jakub-astrahit  Looks like enabling "esModuleInterop": true in tsconfig.json works. Without esModuleInterop it gives the same error as mentioned above. With esModuleInterop: true. This gets fixed. Check about this compiler option in https://www.typescriptlang.org/docs/handbook/compiler-options.html

Check example on https://codesandbox.io/s/8np5110y9. @horacehylee Even the enzyme option works on enabling this flag on your branch.

**Comment by Emiliano-Bucci** [comment]
@s-yadav Is there any solution, other than enabling esModuleInterop in the tsconfig.json? Because this breaks entirely other things.
