### ISSUE TITLE
Decimal values issue on big numbers

### ISSUE THREAD

**Issue by pgrzywa90** [s-yadav/react-number-format#225]
Seems that number format is wrongly setting decimal values for big numbers. Here is the test which reproduces the issue:

```
import React from "react";
import {shallow} from 'enzyme';
import NumberFormat from "react-number-format";

test('should render big number', () => {
  const number = 123456789123456.46;
  const wrapper = shallow(<NumberFormat value={number}/>);
  expect(wrapper.html()).toEqual('<input type=\"text\" value=\"123456789123456.46\"/>');
});

  × should render big number (22ms)

  ● should render big number

    expect(received).toEqual(expected)

    Expected value to equal:
      "<input type=\"text\" value=\"123456789123456.46\"/>"
    Received:
      "<input type=\"text\" value=\"123456789123456.45\"/>"
```

This can be reproduced on newest version of the library (3.6.0)

**Comment by s-yadav** [comment]
The issue is javascript have 64 bit floating point number system. Where 1 bit is for sign, 11 bit for exponent and 52 bit for mantissa. Any number which can not fit on that will loose the precision. 
To check it just paste `123456789123456.46` in your console it will be printed `123456789123456.45`.
The reason behind that is if you remove the decimal point the number will `12345678912345646` which is greater than `Number.MAX_SAFE_INTEGER`.
Its highly advised that you convert your big number (big ints) as string on the server and pass that down. In client side operate on numeric string.
