### ISSUE TITLE
OnClick, selector shouldn't be after prefix/ before suffix

### ISSUE THREAD

**Issue by Elliot128** [s-yadav/react-number-format#29]
Selector should be put before the prefix or after the suffix.

For instance, with prefix '$' you should never be able to type '0$'.
With suffix '%' you should never be able to type '%0'

**Comment by mquandalle** [comment]
Similarly pressing the <kbd>Home</kbd> and <kbd>End</kbd> keys should make a range selection that stop before the suffix / after the suffix.

**Comment by s-yadav** [comment]
Cursor can come before prefix or after suffix , but you can never type 0$ 0 will always will come after $ same with suffix. 
@Elliot128 @mquandalle We shouldn't change the default beviour of keys as it can stop user to do expected operation (like copying the whole text inside input).
I don't think cursor position is a problem till the typed information gets corrected.

**Comment by Elliot128** [comment]
@s-yadav True, you can't actually type '0$' as the 0 gets put in the right place even if the cursor is to the left of the '$'.

**Comment by s-yadav** [comment]
This has been solved to a limit by enforcing cursor to be between prefix and suffix in focus, click or arrow navigation. So user will not be able to type in the middle of suffix or prefix.
But I feel the default behavior of selections should not change, because a user may want to copy whole text along with prefix and suffix.

Check 2.0.0.beta version for the fix. Closing this one.
