### ISSUE TITLE
onFocus={event => event.target.select()} introduces infinite loop bug

### ISSUE THREAD

**Issue by Cadburylion** [s-yadav/react-number-format#293]
If you click on a NumberFormat component that has the property onFocus={event => event.target.select()} to set focus on its contents, then click out of the browser (on another screen, or in the developer console, etc.), then click another NumberFormat component that also has onFocus={event => event.target.select()}, an infinite loop occurs where both inputs constantly set themselves as the focus.

Test an example of this with this [Pen](https://codepen.io/anon/pen/xBYNVW).

Is there currently a way to work around this issue? My use case requires my formatted inputs to have this onFocus function.

**Comment by Cadburylion** [comment]
I seem to have worked around this bug by adding onBlur={event => event.target.blur()} to my NumberFormat component as well.

**Comment by Cadburylion** [comment]
My workaround does prevent the bug I was initially encountering, but the underlying issue remains, and it manifests if you tab very quickly through a series of react-number-format inputs. Doing so will cause an infinite loop where the affected inputs constantly vie for focus.

**Comment by s-yadav** [comment]
@Cadburylion . Thanks for reporting. I cannot reproduce the issue on the codepen you have provided following the mentioned steps. 
Is this on a specific browser? I tried it on chrome.

**Comment by myownzinger** [comment]
@s-yadav  I'm getting the same issue with Number Format elements. Issue takes place in Chrome, haven't tested it on other browsers. I find it most easy to recreate when you're rapidly tabbing through and changing react-number-format inputs. Sometimes the loop is fast and sometimes it is slow. 

As @Cadburylion said, the onBlur workaround doesn't fix this issue, and it's a problem for users who aren't navigating the page with a mouse.

**Comment by edwardkads** [comment]
@s-yadav I also get the same issue with NumberFormat. Did some digging around and it's caused by the setTimeout with a delay of 0 called in the onFocus function.
`setTimeout(() => {
      const el = e.target;
      const {selectionStart, selectionEnd, value = ''} = el;

      const caretPosition = this.correctCaretPosition(value, selectionStart);

      //setPatchedCaretPosition only when everything is not selected on focus (while tabbing into the field)
      if (caretPosition !== selectionStart && !(selectionStart === 0 && selectionEnd === value.length)) {
        this.setPatchedCaretPosition(el, caretPosition, value);
      }

      this.props.onFocus(e);
    }, 0);`
Having a delay of 0 doesn't mean the callback would run immediately as most browsers have it at 4ms but it can be longer than that, see: [https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified](url)

If the timeout is delayed, tabbing through 2 NumberFormat fields would lead to a delayed call for the event.target.select() which would then lead to an infinite calls of the onFocus function between the fields.

This can be replicated by increasing the delay time in the setTimeout.
Fix would be to call clearTimeout in the onBlur function to clear previous timeouts.

**Comment by guipra** [comment]
I'm facing the same issues. `onBlur` workaround works, but doesn't solve the similar rapid-tabbing problem reported.

**Comment by Cadburylion** [comment]
I recently fixed this bug in my affected application by updating to the most recent version of react-number-format (v 4.2.0), removing the onBlur and onFocus functions from my NumberFormat component, and replacing them with onClick={event => event.target.select()}.

**Comment by s-yadav** [comment]
Looks like @edwardkads PR fixes this. Will merge it once failing test cases are added.
