### ISSUE TITLE
Trailing zeros don't get removed

### ISSUE THREAD

**Issue by MakaryHryshkin** [s-yadav/react-number-format#431]
I'm not sure whether it's should be handled by the package. I would be glad about any thoughts.

```
<NumberFormat
    value={1000.2575999999999}
    formatterProps={{ decimalScale: 10  }}
/>
```
React number formatter parses the value above as:

![image](https://user-images.githubusercontent.com/37333016/89396949-e2f2bd00-d717-11ea-9430-28f8a7c7f2c9.png)

Should the trailing zeros be omitted?

**Comment by smacrineanu** [comment]
I have the same issue. It would be pretty stupid it it wasn't handled by the package...

**Comment by s-yadav** [comment]
There is fixedDecimalScale which keeps the trailing zero. Is this happening even with that disabled.?

**Comment by nikhil-varma** [comment]
@MakaryHryshkin Are you still facing this issue?

**Comment by rkulinski** [comment]
@nikhil-varma I am. Seems to still be an issue.

**Comment by nikhil-varma** [comment]
@rkulinski Which version of the library are you using?

**Comment by rkulinski** [comment]
`4.6.2`

**Comment by nikhil-varma** [comment]
@rkulinski Thanks for the info. We will investigate this and keep you posted.

**Comment by nikhil-varma** [comment]
@rkulinski Thanks! Will let you guys know once there is an update on this!

**Comment by ykvarts** [comment]
> @rkulinski Thanks!
> 
> Will let you guys know once there is an update on this!

is there an update on this?

**Comment by nichita-pasecinic** [comment]
Hi @nikhil-varma, 👋  is this still in progress ?

**Comment by nikhil-varma** [comment]
Apologies for the delay. Will sort this out soon.

**Comment by nikhil-varma** [comment]
Hey everyone, we do not yet handle removing trailing zeros by default since that can be a tricky area to handle for now. We do, however, support trailing zeros via the `fixedDecimalScale` prop. We will internally discuss the feasibility of this request and depending on deliberations it may be incorporated in a future release. 

@rkulinski The output you have provided is expected as the `decimalScale` does not account for zeros. It just ensure to add zeros if the count is more than the existing after decimal value.

My humble apologies for the delay in the resolution but I hope it helps. I will close this issue in regard on this comment but please feel free to continue this thread for any further queries

**Comment by nikhil-varma** [comment]
@nichita-pasecinic One quick piece of information, in our latest version v5, we have exposed details to allow customization based on your needs. Please take a look at https://s-yadav.github.io/react-number-format/docs/customization and I believe this use-case can be easily handled with a custom `format`.  I hope this helps. Thanks again!
