### ISSUE TITLE
Component is not updating after changing "fixedDecimalScale" option

### ISSUE THREAD

**Issue by fedulovivan** [s-yadav/react-number-format#455]
Noticed that component sometimes sticks with last value of "fixedDecimalScale" option and not re-renders until some other prop changes.

Reproduction:
step 1: go to official demo at https://codepen.io/s-yadav/pen/bpKNMa
step 2: use following snippet in JS
```js
const { useState } = React;
function App() {
  
  const [fixedDecimalScale, setFixedDecimalScale] = useState(false); 
  
  const toggleFixedDecimalScale = () => {
    setFixedDecimalScale(!fixedDecimalScale);
  }
  
  return (
    <>
  <NumberFormat 
    value="100"
    decimalScale={3}
    fixedDecimalScale={fixedDecimalScale}
  /> 
      <button 
        onClick={toggleFixedDecimalScale}
      >
        toggle (fixedDecimalScale={String(fixedDecimalScale)})
      </button>
      </>
    
  );
  
}

ReactDOM.render(<App />, document.getElementById('app'));
```

step 3: click toggle button several times

Expected zeroes to be added/removed to number on each button click

**Comment by fedulovivan** [comment]
I assume problem resides in function *updateValueIfRequired* in [this line](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L160)

When original value is integer (with no real fractional part) expression `floatValue !== lastFloatValue` returns **false** and therefore formatting remains unchanged.

**Comment by adarshlilha** [comment]
+1 @fedulovivan - Tried out the snippet and it seems the line you pointed out should fix this

**Comment by FayP** [comment]
+1, suffering from a flavour of this too.

**Comment by nikhil-varma** [comment]
@s-yadav Can I pick this up?

**Comment by s-yadav** [comment]
Sure, go ahead.

**Comment by nikhil-varma** [comment]
@fedulovivan I have tested this and the behaviour is as expected. 

Setting `fixedDecimalScale` to `true` forces the value to as per the `decimalScale` provided. But setting that to `false` will not change it back to the original because it doesn't mean that there is no decimal value but it can be a variable within the decimal scale range. 

Ex: If the value is 123.2 and `decimalScale` is set to 3, then passing `fixedDecimalScale` as `true` will force it to be 123.200 (_forces proceeding 0s_). 

Now, setting it to `false`, the value 123.200 is still considered as the correct value since the decimal scale is as per the range provided.

**Comment by BrianValente** [comment]
The component should't render different depending on the previous state, it's confusing.

**Comment by s-yadav** [comment]
@BrianValente how to distinguish between if user has typed trailing 0s or the 0s came from setting fixedDecimalScale prop to true? When the user has typed 0s we shouldn't be removing that, and because of this use-case, we can't reset when fixedDecimalScale is toggled from true to false.
