### ISSUE TITLE
String formatting with decimals <= "0.00000001" are converting wrong

### ISSUE THREAD

**Issue by BrianCorbin** [s-yadav/react-number-format#506]
#### Describe the issue and the actual behavior
When formatting a string <= "0.0000001", it's converting it into

This is a new issue as of 4.5.0, and the current latest working version without this bug I have found is 4.4.4

#### Describe the expected behavior
It should be converting this into 1e-7, not 1e7

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/ppo1kvlwpx?file=/index.js

#### Provide steps to reproduce this issue
type "0.0000001" into the formik field that says "Simple Input Works" and it will turn "0.0000001" into 1e7 and then if you click away it will turn in to 17 in the fields below.

**Comment by nikhil-varma** [comment]
Hey @BrianCorbin ! Thanks for reporting this issue. We will  investigate and pick this up to provide a resolution soon. Keep an eye out for updates!

**Comment by s-yadav** [comment]
Hey @BrianCorbin, I think the real root cause is that the NumberFormat does not support exponential numbers as value prop. So one solution is to use and pass value, or formattedValue from the values object.

The issue was not visible on 4.4.8 as we were converting it to fixed value, so basically it was removing the decimal part of it.
And it got visible by the change we introduced on the v4.5.0 (https://github.com/s-yadav/react-number-format/commit/0619c0445b7f090d40ae1f144b41cca41f2760eb#diff-3274f1a37032fb0ae4e2823def0007c634e869ae0dfc304ff6a12c36513c3a52R93)

We will look into supporting exponential numbers as a separate tasks. But meanwhile don't use the floatValues to pass it back as value prop.
