### ISSUE TITLE
[feature request] Add support for "1M" (for millions) and "1B" (for billions)

### ISSUE THREAD

**Issue by kenneho** [s-yadav/react-number-format#510]
#### Describe the issue and the actual behavior

If I haven't overlooked something, it's not possible for a user to input `1M` (for millions) and `1B` (for billions). Using say `B` as suffix is supported, but it's not possible for a uses to set this suffix directly within the field. 

#### Describe the expected behavior

I'd like a use to be able to seamlessly switch between inputting `1M` and `1B`. Combined with a `$` prefix, a user could seamlessly, within the same field, switch between having the field having value `$900M` and and `$1B`.

**Comment by nikhil-varma** [comment]
@kenneho Thanks for the request. As a part of the core library, I don't think this should be supported because the amount of complexities this would add would introduce tons of edge cases'. Imagine if someone adds `1M` as the value, then the decimal scale handling and other details would become fairly complex to handle. So considering these things, it won't come as a part of this library. 

I hope this helps. Thanks!

**Comment by kenneho** [comment]
No worries. I don't mind handling this edge case in my own code, but don't quite see how. For example, event entering the letter "M" is not allowed. If you have a suggestion for how to handle this edge case myself, I'd really appreciate it.
