### ISSUE TITLE
[QUESTION] When inputmode=numeric is added?

### ISSUE THREAD

**Issue by brunasilva-obj** [s-yadav/react-number-format#520]
#### Describe the issue and the actual behavior
We are doing snapshot testing in a component that use NumberFormat and when we run this test locally the input add
inputmode=numeric but when we run this test on server the test fails because the input does not add inputmode=numeric

Nextjs: 6.1.1
React: 16.8.6
Jest: 23.6.0
Node: 12.16.1
NumberFormat: 4.5.3

#### Describe the expected behavior
Both locally and on server should behave the same

Does anyone know why this may be happening?

**Comment by s-yadav** [comment]
So, adding inputMode=numeric has an issue on iPad and iPhone, the library can't guess the device on SSR. Because of which it only adds inputMode=numeric after mount.
See this reference.
https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L930

As we are adding it after mount, it makes sure, there is no hydration issue.

**Comment by nikhil-varma** [comment]
Hey @brunasilva-obj Closing this issue in consideration of the resolution provided above. Please feel free to reopen this if you have any further questions or any concerns 🙂
