### ISSUE TITLE
How to make react-number-format format the input conditionally?

### ISSUE THREAD

**Issue by luisalbertonunes** [s-yadav/react-number-format#552]
Hello everyone, everything good? In Brazil there are two identification numbers cpf and cnpj, I need to format these two values ​​in the same input. However it doesn't work when I try to do it.

`format={ props.value?.length < 15  ? "###.###.###-##" : "##.###.###/####-##"}`

The input should change the mask according to the number of characters typed. But it doesn't work for me

Here is the codebox, could you help me? I don't know if it would be a bug

https://codesandbox.io/s/still-dawn-qzr2r?file=/src/App.js

**Comment by nikhil-varma** [comment]
Hey @luisalbertonunes , I made some slight changes and here is the link how you can conditionally format it: https://codesandbox.io/s/number-format-custom-conditional-formatting-x9w50

Also a thing to note here is that the condition pivots at length 1 but the issue here is that your format accepts only 11 character (_counting just the #_). The fail case might never come up because the format will limit it to the provided pattern.

Please let me know if the provided solution works or if you need any further help on anything. Happy to help! Thanks! 🙂

**Comment by nikhil-varma** [comment]
@luisalbertonunes I will be closing this issue in light of the response. If you still face any issues or have any questions, please feel free to continue on this thread or re-open it if required. Thanks again for your patience 🙂

**Comment by davidbsoares** [comment]
@nikhil-varma solution is not working. I can't type more digits than the CPF mask supports, thus CNPJ's mask doesn't even appear

**Comment by alissonfernandess** [comment]
you have to use format as a function, that is, you have to create a function that returns in format.
`format={(value) => {
    return AddCpfAndCnpjMask(value);
 }}`

**Comment by caroline-spezzatto** [comment]
The only solution I found was to add an extra character to the CPF format, like this:

```
format={
    field.value?.replace(/\D/g, '')?.length <= 11
    ? '###.###.###-###'
    : '##.###.###/####-##'
}
```
