### ISSUE TITLE
I default zero input and when i onlick or onfocus remove zero default empty

### ISSUE THREAD

**Issue by PokerJava** [s-yadav/react-number-format#663]
#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by coulgreer** [comment]
Howdy there! I would be more than happy to help you, but I'm not entirely sure what the issue is here. You have the template, but have not filled it out; more details or even a snippet of code would help me assist you in overcoming this issue.

I assume that you have a `defaultValue` property that you are setting to `0`, but when you click the `NumberFormat` element or focus on it the default value is removed. I'm just assuming from that information that you use an uncontrolled input element, instead of, a controlled input element. That said, I do not know what the full situation or issue is.

**Comment by PokerJava** [comment]
When I onfocus I want to set value ' ' 
![Screen Shot 2565-08-30 at 00 20 18](https://user-images.githubusercontent.com/26649959/187259190-fee32698-9545-417d-90ab-36f42d4f4579.png)
<img width="447" alt="Screen Shot 2565-08-30 at 00 21 09" src="https://user-images.githubusercontent.com/26649959/187259507-4d7d2084-a16f-45bb-934a-c97a2d0f505d.png">

**Comment by PokerJava** [comment]
I use CustomInput component
<img width="858" alt="Screen Shot 2565-08-30 at 00 22 30" src="https://user-images.githubusercontent.com/26649959/187260025-59e0ecf0-883a-43ee-b534-26b25849b334.png">

**Comment by coulgreer** [comment]
I believe I see what the issue is. The `placeholder` prop will always take over when there is no value in your input field. To allow for a default value you can use `state` either as a hook or class and set the value of the state when intially building the component. It will allow the field to be empty, but you can set the value using the `onBlur` prop to circumvent that.

I'm not entirely sure why you have a `setFieldValue` prop as well. That should be handled elswehere, not by the component itself. Elsewhere being the prop of `onFocus`, `onChange`, `onBlur`, etc., but that's just be my opinion on the matter.

If that is not the solution you're seeking or my solution does not work, I can try to fiddle around in Codesandbox and give you a proper example.

**Comment by PokerJava** [comment]
thank you english are not good.

I use onFocus and set ' ' and onBlur set 0  working
I use formik setFieldValue sorry
