### ISSUE TITLE
No number type support

### ISSUE THREAD

**Issue by TimeTerminal** [s-yadav/react-number-format#686]
#### Describe the issue and the actual behavior
`type=number` doesn't allow input in the component, which is horrible for accessibility.

#### Describe the expected behavior
The component should allow `type=number`. I see this in the [roadmap](https://github.com/s-yadav/react-number-format/discussions/564) being planned for V5, but v5 is out and I don't see this in the changelog anywhere.

#### Provide a CodeSandbox link illustrating the issue
N/A

#### Provide steps to reproduce this issue
Use `type=number` but the library stops working

#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [x] Firefox (Android)

**Comment by nikhil-varma** [comment]
Hi @TimeTerminal 

We really cannot support type as number because then it'll take away the ability to manipulate and add non numeric characters. We will basically loose the essence of what this library provides. I hope this helps clarify the idea. 


I'll close this issue but please feel free to reopen the thread in case you have any questions. Thanks!

**Comment by RuellePaul** [comment]
Hi @nikhil-varma ,

It's true that in mobile, using this library (to format amounts in euros for example) is problematic because it's not the numeric keypad that is displayed.

I understand that the native technical limitation in HTML does not allow non numeric characters - but wouldn't it be possible to have a `<input type="text"/>` for rendering and a `<input type="number"/>` for input ? (the latter would be on top of the former)
