### ISSUE TITLE
Incorrect behaviour when precision enabled and 0 with precision

### ISSUE THREAD

**Issue by s-yadav** [s-yadav/react-number-format#70]
If field already contains zero value like '0.00' and at the beginning of input you will get '10.00' instead of '1.00'

**Comment by adamshone** [comment]
As a workaround I just have it select all on focus, so the user can start typing and get the expected behaviour. But it's still noticeable if you delete the whole contents of the input and then start typing.
```
onFocus({target}) {
  target.select();
}

render() {
  return <NumberFormat onFocus={this.onFocus} />;
}
```
As a side-note, it would be nice if it the input accepted a value of `''` and rendered nothing, rather than render a value of `0.00`. That would allow me to use the placeholder to indicate the format of the input.

**Comment by haseebsaif** [comment]
If field already contains zero value like '0.00' and at the beginning of input you will get '10.00' instead of '1.00'

I am still getting this same behavior. When i backspace everything from the field i get 0.0 at the end and my cursor is at very beginning. Now, Lets say you type 1, it give me 10.0 instead of 1.0.

How to overcome that? Will appreciate the help.

**Comment by alizakushner** [comment]
Having this issue as well, if user backspaces it shows 0 and cursor moves the the beginning of the input
