### ISSUE TITLE
Thousand and decimal formatting broken while typing when valueIsNumericString is set to false with react-final-form

### ISSUE THREAD

**Issue by Nico924** [s-yadav/react-number-format#741]
#### Describe the issue and the actual behavior
When using react-number-format with react-final-form where I need to store the **floatValue**, if I set the parameter valueIsNumericString to false even if I provide a numeric value to NumericFormat, the formatting of the input text is not done while typing.
If I remove valueIsNumericString or if I set it to true (even with numeric value) or undefined, it works.

#### Describe the expected behavior
I would like the decimal and thousand formatting to work while typing.

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/embed/react-final-form-w-react-number-format-forked-7byc8q?fontsize=14&hidenavigation=1&theme=dark

#### Provide steps to reproduce this issue
Start writing anything in the input (adding 0 for example), no formatting will occur

**Comment by TheSharpieOne** [comment]
Running into this as well, but without `react-final-form`.  From what I can tell, internally the value is _always_ a string, and setting `valueIsNumericString` to `false` makes it not perform the string formatting (in fact, it makes it remove the formatting.)

Here is the code that is doing that: https://github.com/s-yadav/react-number-format/blob/11af4c5e76c265656ea3a0fa620bb26912cb9cc0/src/utils.tsx#L430-L439
Now you may be thinking `typeof value === 'number'` would be `true`, we are supplying a number. But it is always a string at this point (when getting the input's value to be displayed). It uses `roundIncomingValueToPrecision` as the `value` when passing it to `useInternalValues` and returns `formattedValue` which isn't formatted in this case.
https://github.com/s-yadav/react-number-format/blob/11af4c5e76c265656ea3a0fa620bb26912cb9cc0/src/numeric_format.tsx#L376-L383
Here is `roundIncomingValueToPrecision` and you can see if the value is a number, it will make it a string
https://github.com/s-yadav/react-number-format/blob/11af4c5e76c265656ea3a0fa620bb26912cb9cc0/src/numeric_format.tsx#L358-L374
Here is that `formattedValue` being returned as `value`. This returned value is later passed to `NumberFormatBase`
https://github.com/s-yadav/react-number-format/blob/11af4c5e76c265656ea3a0fa620bb26912cb9cc0/src/numeric_format.tsx#L479-L490
https://github.com/s-yadav/react-number-format/blob/11af4c5e76c265656ea3a0fa620bb26912cb9cc0/src/numeric_format.tsx#L493-L499
`NumberFormatBase` actually runs `useInternalValues` again. This time is it with the value from that previous run that is already a string at this point.

Here is a sandbox without final form: 
https://codesandbox.io/s/float-value-demo-qrw2l7

Assuming what the above is correct, setting this to always be `true` would fix the issue since it is always passing a string to the function:
https://github.com/s-yadav/react-number-format/blob/11af4c5e76c265656ea3a0fa620bb26912cb9cc0/src/numeric_format.tsx#L379
OR after rounding, convert it back to a number.

**Comment by s-yadav** [comment]
@TheSharpieOne thanks for digging on this.
Yes, looks like a bug. I was doing some refactoring around guessing if a value is a numeric string based on the prop. Will fix it along with that.

**Comment by jcrawl3y** [comment]
@s-yadav Confirming that this bug is occurring to me too.  Do you have a rough estimate on when this fix will be available?

**Comment by s-yadav** [comment]
This is fixed on v5.2.0
