### ISSUE TITLE
How to preserve the suffix in a NumericFormat when to value is empty?

### ISSUE THREAD

**Issue by CharlesCoqueret** [s-yadav/react-number-format#773]
How can I setup NumericFormat to preserve the suffix or prefix when the value is empty?
The use case is for currency.

To reproduce:
https://codesandbox.io/embed/suffice-demo-forked-tyvmpd
When the value is empty, the suffix is not displayed.

Thanks for you help.

**Comment by s-yadav** [comment]
`allowEmptyFormatting` is PatternFormat props. It's not a part of the NumericFormat as in most of the cases it's not intentional behaviour.

Though you can easily achieve it using our custom format. Here's the updated codesandbox.
https://codesandbox.io/s/numeric-format-allowemptyformat-zt3mh8

More on customization: https://s-yadav.github.io/react-number-format/docs/customization

**Comment by s-yadav** [comment]
Will add this on the documentation as well.

**Comment by CharlesCoqueret** [comment]
Perfect, thanks.

**Comment by wilfredjonathanjames** [comment]
Hey @s-yadav can I ask why this isn't intended behaviour for numerics?

If it's a price field for instance it needs to be obvious that it's a price field. Even when empty. Otherwise it's just a field. Prefix `$` with `allowEmptyFormatting ` would solve this, so I'm curious why you decided not to include it. I've seen issues about this dating back almost 3 years.

`in most of the cases it's not intentional behaviour` - can you tell me where you're getting your data on this?
