### ISSUE TITLE
Support character input in combination with format

### ISSUE THREAD

**Issue by pudgereyem** [s-yadav/react-number-format#84]
Another issue, partially related to https://github.com/s-yadav/react-number-format/issues/83 (since it deals with personal identity numbers)

## Background
In Finland people have a personal identity code. If interested you can see how it's made up here; http://vrk.fi/en/personal-identity-code1

## Issue
Finnish personal identity code can hold both numbers and characters, with the syntax `######-###X`, where `#` is a digit, and `X` could be a digit or a character. Example, 131052-308T.

I would like to use format, but still offer the user to enter a character in the end. As far as I understand this is not possible atm.

## Solution
TBD

---

Thoughts on this @s-yadav?

**Comment by s-yadav** [comment]
This one will be hard to implement. Because if allow alpha numeric character we have to handle a lot of case/problems. 
1. If we add #83 what if one of the mask input is a character, how we will distinguish between what is inputted character and what is mask character. 
2. Regex to extract valid input from the user will get complex. Regex should handle valid character at the specific position while allowing masking. Which will bring third issue
3. We can shift numbers if type valid input in between like for pattern ####
`6 on 45|33 -> 4563 . `
This will be hard if regex is doing position based validation lets say if formatting is ##X##
`6 on 4|5T67 -> 465T6 (Third and fourth position will be invalidated)`

Overall I am not in favour of implement this.

**Comment by pudgereyem** [comment]
@s-yadav Good points, it would get complex if we were to allow both numbers and characters in format. I didn't think about that initially.

---

However, what I think we could do is to add "character support" to format, is the option to toggle between accepeting:

1. only numbers (current state)
2. both numbers and characters

This could sit in a prop such as `formatAcceptCharacters=true`. In the example above, I would then do the following:

```
<Input 
  format="######-####"
  formatAcceptCharacters={true} />
```

This would allow to write ABC123-X0Y9, for example.

**Comment by s-yadav** [comment]
I will keep it as out of the scope of number format as the primary focus of this module is to format just numbers and also this will make the formatting logic much more complex. 
I am also sceptical about supporting alphanumeric characters as it opens up a lot more use cases.
