### ISSUE TITLE
pointer position is resetted if value is number

### ISSUE THREAD

**Issue by raDiesle** [s-yadav/react-number-format#851]
#### Describe the issue and the actual behavior

- when number type value is passed to the input, its cursor is jumping in > v4, because value ".00" is considered different than 0 

https://github.com/s-yadav/react-number-format/issues/850

#### Describe the expected behavior
- cursor is never jumping. in the component there should be a Number(value) === Number(prevValue) check, which will ignore types, like it was on v5

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/p/sandbox/alloweddecimalseparators-demo-forked-4z33vm

#### Please check the browsers where the issue is seen
- [X ] Chrome

**Comment by s-yadav** [comment]
`Number(value) === Number(prevValue)` won't work as formatted value can change due to change on format props as well. prefix/suffix, separator etcs. 

Anyways this would happen, only when user is typing decimal character on empty input with decimalScale and fixedDecimalScale set. Putting a fix around this.

**Comment by s-yadav** [comment]
Fixed on 5.4.1
