### ISSUE TITLE
fixLeadingZero function does not handle custom decimalSeparator properly

### ISSUE THREAD

**Issue by francesc79** [s-yadav/react-number-format#875]
#### Describe the issue and the actual behavior
when enter and exit to the input the value change from 0,00 to ,00 

#### Describe the expected behavior
expected that the value not change

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/p/sandbox/9fh9ww
Click on an input field, then click outside the input field without making any changes to lose focus.

#### Provide steps to reproduce this issue
The issue is in the fixLeadingZero function. The function does not receive a decimalSeparator and uses numStr.split('.') to split the value. In my case, the decimalSeparator is ','.

#### Please check the browsers where the issue is seen
- [x ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
Will check this. Thanks for reporting.

**Comment by s-yadav** [comment]
@francesc79 the issue is due to `valueIsNumericString` being passed incorrectly. The passed valus is formatted string, but the  valueIsNumericString say's otherwise.
https://s-yadav.github.io/react-number-format/docs/props#valueisnumericstring-boolean

Here is the example without valueIsNumericString.
https://codesandbox.io/p/sandbox/react-number-format-issue-forked-rpklhm?file=%2Fsrc%2FApp.tsx%3A12%2C11
